#!/usr/bin/env bash

# Used by Docker Hub to replace the normal autobuild build script

# Windows (Gitlab-CI) Build -- Python2
docker build --no-cache -t engineervix/pyinstaller-windows-ci:python2 . --network=host
